version: "3"
services:
  webserver:
    image: "stevando:moodle-docker"
    depends_on:
      - db
    volumes:
      - "${MOODLE_DOCKER_WWWROOT}:/var/www/html"
      - "${ASSETDIR}/web/apache2_faildumps.conf:/etc/apache2/conf-enabled/apache2_faildumps.conf"
    tmpfs:
      - /muc
    environment:
      MOODLE_DOCKER_DBNAME: "${MOODLE_DOCKER_DBNAME}"
      MOODLE_DOCKER_DBUSER: "${MOODLE_DOCKER_DBUSER}"
      MOODLE_DOCKER_DBPASS: "${MOODLE_DOCKER_DBPASS}"
      MOODLE_DOCKER_BROWSER: "${MOODLE_DOCKER_BROWSER}"
      MOODLE_DOCKER_WEB_HOST: "${MOODLE_DOCKER_WEB_HOST}"
    ports:
      - "443:443"
  exttests:
    image: moodlehq/moodle-exttests
    volumes:
      - "${ASSETDIR}/exttests/apache2_ports.conf:/etc/apache2/ports.conf"
      - "${ASSETDIR}/exttests/apache2.conf:/etc/apache2/sites-enabled/000-default.conf"
  selenium:
    image: "selenium/standalone-firefox${MOODLE_DOCKER_SELENIUM_SUFFIX:-}:${MOODLE_DOCKER_BROWSER_TAG}"
    volumes:
      - "${MOODLE_DOCKER_WWWROOT}:/var/www/html:rw"
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev", "--import-realm"]
    volumes:
      - "./keycloak/data:/opt/keycloak/data"
      - "./keycloak/keycloak.conf:/opt/keycloak/conf/keycloak.conf"
      - "./moodle_dev/assets/certs/:/etc/ssl/certs/"
    ports:
      - 8080:8080
      - 8443:8443
    environment:
      KEYCLOAK_ADMIN: "${KEYCLOAK_ADMIN}"
      KEYCLOAK_ADMIN_PASSWORD: "${KEYCLOAK_ADMIN_PASSWORD}"
    healthcheck:
      test: [ "CMD", "curl", "-f", "-k", "https://keycloak:8443/realms/moodle/.well-known/openid-configuration" ]
      interval: 30s
      timeout: 10s
      retries: 5
  synapse:
    image: "matrixdotorg/synapse:latest"
    volumes:
      - "./synapse_data:/data:rw"
      - "./moodle_dev/assets/certs/:/etc/ssl/certs/"
    environment:
      SYNAPSE_SERVER_NAME: "synapse"
      SYNAPSE_REPORT_STATS: "yes"
    ports:
      - "8008:8008"
      - "8448:8448"
    depends_on:
      - keycloak
    restart: on-failure
  element:
    image: vectorim/element-web
    volumes:
      - "./element_data/config.json:/app/config.json"
      - "./element_data/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./moodle_dev/assets/certs/:/etc/ssl/certs/"
    ports:
      - "8081:8081"
    depends_on:
      - synapse
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.32.238.0/24
          gateway: 172.32.238.1
