// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Handles react import aliases
 *
 * @copyright  2025 Adrian Greeve
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

import fs from "fs";
import path from "path";

const rootDir = process.cwd();
const publicDir = path.join(rootDir, "public");
const esbuildDir = path.join(rootDir, ".esbuild");

// Generated by .esbuild/generate-aliases.js
const aliasesPath = path.join(esbuildDir, "react-aliases.json");

/**
 * Load alias patterns like:
 *   "@moodle/core/*": "public/lib/react/src/*"
 *
 * And convert to a prefix map like:
 *   "@moodle/core/": "<root>/public/lib/react/src"
 */
function loadAliasMap() {
    if (!fs.existsSync(aliasesPath)) {
        return {};
    }

    const raw = JSON.parse(fs.readFileSync(aliasesPath, "utf8"));

    /** @type {Record<string, string>} */
    const map = {};

    for (const [pattern, targetPattern] of Object.entries(raw)) {
        const aliasPrefix = pattern.replace(/\*$/, ""); // "@moodle/core/"
        const targetRootRel = String(targetPattern).replace(/\/\*$/, ""); // "public/lib/react/src"
        map[aliasPrefix] = path.join(rootDir, targetRootRel);
    }

    return map;
}

function toBrowserPath(value) {
    return value.split(path.sep).join("/");
}

function ensureRelativeSpecifier(specifier) {
    if (specifier.startsWith(".") || specifier.startsWith("/")) {
        return specifier;
    }
    return `./${specifier}`;
}

function getOutputDirForImporter(importer) {
    const marker = `${path.sep}react${path.sep}src${path.sep}`;
    const idx = importer.lastIndexOf(marker);

    if (idx === -1) {
        return path.dirname(importer);
    }

    const before = importer.slice(0, idx);
    const after = importer.slice(idx + marker.length);
    const subDir = path.dirname(after);

    return path.join(before, "react", "build", subDir === "." ? "" : subDir);
}

function buildRelativeRuntimePath(importer, target) {
    if (!importer) {
        const relativeToPublic = path.relative(publicDir, target);
        return ensureRelativeSpecifier(toBrowserPath(relativeToPublic));
    }

    const importerOutputDir = getOutputDirForImporter(importer);
    const relativePath = path.relative(importerOutputDir, target);
    return ensureRelativeSpecifier(toBrowserPath(relativePath));
}

function escapeRegExp(value) {
    return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

export function createAliasPlugin() {
    const aliasMap = loadAliasMap();

    // Sort by longest prefix first so "@moodle/core_ai/" beats "@moodle/core/"
    const aliasEntries = Object.entries(aliasMap).sort(
        (a, b) => b[0].length - a[0].length
    );

    return {
        name: "moodle-aliases",
        setup(build) {

            // Component alias resolution (internal, resolved to real files)
            aliasEntries.forEach(([aliasPrefix, targetDir]) => {
                const filter = new RegExp(`^${escapeRegExp(aliasPrefix)}(.*)$`);

                build.onResolve({ filter }, async (args) => {
                    const relPath = args.path.slice(aliasPrefix.length);

                    return await build.resolve(`./${relPath}`, {
                        resolveDir: targetDir,
                        kind: args.kind,
                    });
                });
            });
        },
    };
}
